version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: Milk
    ports:
      - '8500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: MilkRedis
    ports:
      - '6479:6379'
    volumes:
      - redisDB:/data
volumes:
  progresDB:
  redisDB:


